### PR TITLE
Add LDAP documentation 

### PR DESCRIPTION
**Pull request by amarjayr**
Documentation for https://github.com/getredash/redash/pull/1836

### CODE REVIEW

**Comment by jeffwidman** [comment]
nudge @arikfr

**Comment by jeffwidman** [comment]
bump @arikfr anything holding this up?

**Comment by dalenoe** [comment]
Dang, I have been hoping to see this implemented.

**Comment by jeffwidman** [comment]
It is implemented, we use it in production. It's just the docs that haven't been merged yet.

**Comment by arikfr** [comment]
Merged. Thank you for your patience  :)

**Pull request merged**
