### PR TITLE
Bump Node.js, Gatsby, and package version

### PR DESCRIPTION
**Pull request by lucydodo**
> [!NOTE]
> A newly opened PR due to a technical issue with an existing PR.
> Previously left conversations, reviews, etc. can be found in the #695 PR.

> [!CAUTION]
> This PR contains BREAKING CHANGES.
> I've tested it on a number of cases, but we should take the review with a grain of salt.

## Major changes
1. Upgrade Node.js engine version (10 -> 20.x LTS)
2. Upgrade Gatsby version (2 -> 5)
3. Upgrade related dependency package versions
4. Fix security vulnerabilities of concern due to outdated package versions.
5. Configure ESLint and fix
6. Make Docker work for the above changes

I look forward to any comments and reviews. and also if you have any questions, feel free to ask.
Thank you. :)

### CODE REVIEW

**Comment by justinclift** [comment]
@lucydodo If you want, I can take a look at this tomorrow sometime to see if I can spot any broken things again?

**Comment by lucydodo** [comment]
I was unable to fix the bug I mentioned last time, so I've reached out to @arikfr for advice.
Once I fix that bug, would you mind if I deploy it again via Netlify and ask you to test it?

**Comment by justinclift** [comment]
Of course.  I'm too tired to really do anything super useful today (that needs attention to detail), but should be fine tomorrow. :smile:

**Comment by lucydodo** [comment]
Rest is important, It's the weeknd, so get some rest. :)

**Comment by lucydodo** [comment]
@justinclift You can test this PR by following the following link. :)
btw, the issue we mentioned last time seems to be resolved. https://deploy-preview-703--redashio.netlify.app

**Review by eradman — CHANGES_REQUESTED** [review]
Also update `README.md` which has some old instructions:

> This seems to depend on Node v10. Until the dependencies updated to support newer versions of Node, you can use the Docker setup.

**Comment by justinclift** [comment]
> Until the dependencies updated to support newer versions of Node, you can use the Docker setup.

In this situation, that phase is saying things are limited to Node 10 due to the dependencies in this project.  There were probably some in use that _required_ Node 10 at the time, which is probably not how things are now. :smile:

**Comment by lucydodo** [comment]
Cool, I understand. I don't think we need that guidance, at least for now, so I'll delete it. Thank you @justinclift

**Review by eradman — COMMENTED** [review]
I think this restyle error is unrelated. We can address this separately or in this change

```
static/assets/scripts/a.js: SyntaxError: Missing semicolon. (34:6)
  32 |         return analytics
  33 |       }
> 34 |     } for (var t = 0; t < analytics.methods.length; t++) {
     |      ^
  35 |       var e = analytics.methods[t]
  36 |       analytics[e] = analytics.factory(e)
  37 |     }
```

**Comment by lucydodo** [comment]
@eradman Thank you, I think we should reconfigure Linter, and I personally think it's better to split into different PRs. :)

**Comment by lucydodo** [comment]
If we finalize this PR and set up Linter, we may need to create another PR (one that fixes the styles for this PR),
so is it a good approach to set up Linter anew first? 🤔

**Comment by eradman** [comment]
Based on the netlify.app preview this appears to be in good shape

**Comment by lucydodo** [comment]
@eradman Thank you for review. :)
Lastly, @justinclift was reviewing it, but it looks like he's still busy with the migration work, can we wait for his review and then merge it?

**Comment by justinclift** [comment]
Oops, I totally forgot about this.  @eradman reckon's it's in good shape though, so we're probably fine to merge it and if anything weird shows up later we can fix it then. :smile:

**Comment by lucydodo** [comment]
Cool, Let's merge. :)

**Pull request merged**
