### PR TITLE
Update docker.md to catch other error code

### PR DESCRIPTION
**Pull request by adrienthiery**
I encountered `errno 134` and not `errno 137` while running it for the first time.

Thought it would be good to add.

### CODE REVIEW

**Comment by arikfr** [comment]
@adrienthiery and increasing memory resolved it?

**Comment by adrienthiery** [comment]
Yes, sir 🙂

**Comment by arikfr** [comment]
Was it with a recent version of the master branch? Since this was written we reduced the webpack memory needs.

**Comment by adrienthiery** [comment]
The one from 13 or 14 days ago, I would say 😅

**Comment by arikfr** [comment]
I'm pretty sure this is no longer needed, but merging in just in case. Thnanks!

**Pull request merged**
