### PR TITLE
env-vars-settings: Sort items alphabetically

### PR DESCRIPTION
**Pull request by lucydodo**
This is a change to what we've already [discussed](https://discord.com/channels/1029619790563790848/1029619790563790851/1267753888514179082) in our Discord channel.
As an aside, I think the commit title is a bit messy, any ideas? 🤔

### CODE REVIEW

**Comment by eradman** [comment]
> As an aside, I think the commit title is a bit messy, any ideas?

Yes, just make the title of this commit "env-vars-settings: Sort items alphabetically"

**Comment by lucydodo** [comment]
@eradman Thanks, I've changed the commit title.

**Review by eradman — APPROVED** [review]
Checked https://deploy-preview-735--redashio.netlify.app/help/open-source/admin-guide/env-vars-settings/

Looks good!

**Comment by lucydodo** [comment]
Thanks for the review. :)

**Pull request merged**
