### PR TITLE
Add docs: Formatting numbers in visualizations

### PR DESCRIPTION
**Pull request by kravets-levko**
We use `numeral` to format numbers, but we changed it's behavior a bit, and it does not match `numeral`'s docs. Possible solution is to move that docs to the knowledgebase and fix it according to our changes.

image

### CODE REVIEW

**Comment by kravets-levko** [comment]
@arikfr @kocsmy It's my first PR to this repo, so please check if I'm doing everything right.

**Comment by kocsmy** [comment]
This looks good, a few comments:
- Might be good to add some basic description at the beginning.
- Is this linked from anywhere? We should point some links to this page.

**Comment by kravets-levko** [comment]
@kocsmy 

> Might be good to add some basic description at the beginning.

Will do. Also, will appreciate any suggestions what to put there.

> Is this linked from anywhere? We should point some links to this page.

Primarily this page is for using in Redash app instead of linking to http://numeraljs.com/. But it's also available in Visualizations category on knowledgebase:
image

**Comment by tkym77xyz** [comment]
Hi

Percentages format(numeraljs) seems to be wrong with redash v5.

You fixed numeral's docs, but I think it's much better to fix visualization behavior.

Could I ask why you fixed numeral's docs ?

If you had any specific reason, I want to know it.

http://numeraljs.com/

image

Best regerds !!

**Comment by kravets-levko** [comment]
Hi @tkym77xyz! Please see my [comment](https://github.com/getredash/redash/issues/2901#issuecomment-429757277)

**Comment by tkym77xyz** [comment]
Sorry, I understand.
Thanks !

**Comment by arikfr** [comment]
I added an intro paragraph and merged. 👍

**Comment by kravets-levko** [comment]
Thanks a lot @arikfr!

**Pull request merged**
