### PR TITLE
HelpDrawer “Open in New Window” button WIP

### PR DESCRIPTION
**Pull request by ranbena**
Discussion here https://discuss.redash.io/t/should-the-help-drawer-retain-state/3832/8.
Depends on https://github.com/getredash/redash/pull/3880.

Screen Shot 2019-06-04 at 14 54 04

### CODE REVIEW

**Comment by ranbena** [comment]
@arikfr I just realized that the current design's dependency on https://github.com/getredash/redash/pull/3880 makes it impractical cause previous Redash versions would present this unacceptable UX problem.

Screen Shot 2019-06-05 at 17 53 14

So, 2 options ahead of us:
1. Find an alternative design that can work with such a large button. Here's something that can work but I don't love it.


2. Fallback to [option 1](https://discuss.redash.io/t/should-the-help-drawer-retain-state/3832/10) in the discussion.

**Comment by gabrieldutra** [comment]
Perhaps you can use a new class selector instead of `body:not(.drawer)` introduced in the dependency PR? This way it will appear only for the new code.

**Comment by ranbena** [comment]
> Perhaps you can use a new class selector introduced in the dependency PR instead of `.drawer` for `body:not(.drawer)` ? This way it will appear only for the new code.

That's a great idea!
But deep inside I know this is the wrong approach and implementing option 2 won't be such a hassle.

**Comment by ranbena** [comment]
> Perhaps you can use a new class selector introduced in the dependency PR instead of .drawer for body:not(.drawer) ? This way it will appear only for the new code.

Actually @gabrieldutra I'm not sure how that would have worked. The `.drawer` classname doesn't come from the parent window but from within the website (determined by `window.parent !== window`).

**Pull request closed without merging**
