### PR TITLE
Update Redash upgrade instructions and compose file

### PR DESCRIPTION
**Pull request by mirkan1**

### CODE REVIEW

**Comment by justinclift** [comment]
Super cool, thanks.  Eyeballing this, it seems pretty straight forward and looks correct. :smile:

**Review by justinclift — APPROVED** [review]

**Comment by lucydodo** [comment]
Screenshot 2024-04-29 at 15 35 42
I think you're forgetting to squash the commits. Why don't we revert the commit, squash it, and push it again?

**Comment by mirkan1** [comment]
To be honest, I am not sure how that would work at this point

**Comment by justinclift** [comment]
> Why don't we revert the commit, squash it, and push it again?

Oops, I totally forgot.  Um, do you want to fix it?  If you can't be bothered, I can get it done. :smile:

**Comment by justinclift** [comment]
@mirkan1 It's not super hard to fix.  It just needs a bit of manual mucking around to merge those into a single commit before force pushing it back to the repo. :smile:

**Comment by lucydodo** [comment]
@mirkan1 Sorry, I forgot to mention @justinclift, we can take care of that ourselves.
@justinclift I'll do it. :)

**Comment by justinclift** [comment]
@lucydodo Cool, thanks heaps.  I wouldn't have even noticed for ages, and by then we'd probably have added more stuff. :smile:

**Pull request merged**
