### PR TITLE
Bump Node.js, Gatsby, and package version

### PR DESCRIPTION
**Pull request by lucydodo**
> [!CAUTION]
> This PR contains BREAKING CHANGES.
> I've tested it on a number of cases, but we should take the review with a grain of salt.

> [!CAUTION]
> We should revert commit 470616b5de3e369accf19718b036fb0ea416abf0 before merging.

## Major changes
1. Upgrade Node.js engine version (10 -> 20.x LTS): 8d387f9907b8bd457b14d512c0c88278641c8338
2. Upgrade Gatsby version (2 -> 5)
	- 3ea0c16559c4c924fb67a678001daf9f456cd2f6
	- 703110df82f448410ded0eeaa307d7cd171d0ee8
	- 907f4e36f8e2cbaf7b2db9ad16d14021ae96ead4
	- c512ff2e5885742836fe9c24c11d0832adb99c95
	- 2446011d711ac38ca059a7c8838c7a2b5a0a4856
	- be43f7eadeb7f9b19709cfbc5fc974184e366065
	- 95cd7faec9e426a340ab45dbcd594d4ae2ddf462
	- 6cd6b8fb901baf572cfb18a360c687b8c555201c
3. Upgrade related dependency package versions
	- 3ea0c16559c4c924fb67a678001daf9f456cd2f6
4. Fix security vulnerabilities of concern due to outdated package versions.
	- 3ea0c16559c4c924fb67a678001daf9f456cd2f6
	- 2f7de9f0425d2523c80afc905391c846b9a212fe
5. Configure ESLint and fix : c6bf558c556fe4b9cbebea288698341d05ffcdeb
6. Make Docker work for the above changes: b0214f5f645f918924d72f26869b1138ac4acb96

## How to test this PR
I'm deploying through my AWS. You can test it at the following link: https://redash.lucydodo.com

I look forward to any comments and reviews. and also if you have any questions, feel free to ask.
Thank you. :)

### CODE REVIEW

**Comment by lucydodo** [comment]
A runtime error has been reported for the `/help/user-guide/` subpath, I'm checking now.

**Review by lucydodo — COMMENTED** [review]
A runtime error has been reported for the /help/user-guide/ subpath, I'm checking now.

**Review by lucydodo — COMMENTED** [review]
~~It was reported that an image was not output from `/help/user-guide/visualizations/pivot-table-visualizations/'.~~
Fixed via e64233273ce1b5ffc04f2378b87f092b17a43e3a

**Review by lucydodo — COMMENTED** [review]
An issue was reported where links would fail to render when served usign `{% link %}` syntax.
I'm working on a fix, but it's likely to take some time. :(

**Comment by justinclift** [comment]
Hmmm, I wonder if we should do something about this `restyled` CI check too.  It was more annoying than useful in the `setup` repo, but it might actually serve a useful purpose (unsure).

**Comment by lucydodo** [comment]
Yes, I am aware of this and I will have to address it, but for now I want to test the site to make sure it works first, otherwise the style change will cause a lot of changes that will be a bit difficult to debug. :)

**Comment by justinclift** [comment]
Cool, makes sense. :smile:

**Comment by lucydodo** [comment]
I tried to change the branch of the head repo with the PR open due to a tangle of commits in the branch,
but it didn't work, so I was forced to open a new PR. I apologize for the hassle. New PR: #703

**Comment by justinclift** [comment]
No worries at all. :smile:

**Pull request closed without merging**
