### PR TITLE
Update to NodeJS packages, to fix vulnerable packages warning

### PR DESCRIPTION
**Pull request by justinclift**
The changes here are from running "npm audit fix", to resolve a warning with the current package set:
```
audited 29427 packages in 18.505s
found 31 vulnerabilities (1 low, 14 moderate, 16 high)
```

Tested on a new CentOS 7 install, with NodeJS 10.16.0 LTS.

### CODE REVIEW

**Comment by gabrieldutra** [comment]
One issue I see is that the website actually uses `yarn` :sweat_smile:. ([GH issue](https://github.com/yarnpkg/yarn/issues/7075)).

Since there's no equivalent to `npm audit fix` perhaps upload the `yarn.lock` after a `yarn install` instead of the `package-lock.json`?

**Comment by justinclift** [comment]
Heh Heh Heh.  Fails on the deloy/netlify check.  Oh well, better to catch problems early. :wink:

**Comment by justinclift** [comment]
Thanks, attempt 2 coming up. :smile:

**Comment by justinclift** [comment]
Is this `package-lock.json` file needed?

&nbsp; &nbsp; https://github.com/getredash/website/blob/master/package-lock.json

**Comment by justinclift** [comment]
Note that this PR doesn't change the package-lock.json file, even though it exists in the repo.

As a 2nd note... these vulnerabilities **probably** don't matter for a static site generator, so this may not be a good thing to put time into. :wink:

**Comment by justinclift** [comment]
Meh, going to close this.  It keeps failing, and these pieces are for a static site generator, so shouldn't have any real world implications.

**Pull request closed without merging**
