### PR TITLE
Updating documentation images, content and refreshing style

### PR DESCRIPTION
**Pull request by kocsmy**

### CODE REVIEW

**Comment by arikfr** [comment]
1. The images are very wide. Is this intentional? This creates heavier images, but also means that it's harder to see the details without enlarging.
2. Why the green color for annotations? :)

**Comment by kocsmy** [comment]
1. The images are approx. the same size as we had previously. It shouldn't be wider as it was.
2. It was red, I wanted something less red so I went with green :)

**Comment by kocsmy** [comment]
Re 1: Ok, I realised what you're pointing out. 

The previous images were focused on one little part of the UI. I wanted to provide more context and show the entire page (so it's easier to locate where you are). That's the reason you can see more, like here: 
screenshot 2018-04-16 12 27 54

Previously this only showed the form, which made it hard to locate that you must be on "Account" tab in the Settings page.

**Comment by arikfr** [comment]
OK, it makes sense to show the full screen. But let's use smaller screen size, maybe something like `1200x800`? We can keep the ones you did as is.

**Comment by kocsmy** [comment]
I'm using the standard 15 inch full screen as a default size.

**Comment by arikfr** [comment]
I know :) hence the suggestion to make a smaller size. `1200x800` is the cut off resolution after which some UI gets changed for responsivness, and it generates ~20% smaller images.

**Comment by arikfr** [comment]
Merged. I didn't review all images as it was too tiring... but I assume it can't be worse than the outdated ones we currently have :-) 

Also I didn't use the gif for grouping dashboards as it showed the non-tags way.

**Pull request merged**
