### PR TITLE
Add documentation for funnel chart

### PR DESCRIPTION
**Pull request by tonyjiangh**
I wasn't able to show the picture in my dev env.
Not sure if this is all though.

- related issue: https://github.com/getredash/redash/issues/2404

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks!

The reason the picture didn't work for you was because you don't need to use the Netlify domain (current images use it, because of the auto conversion from HelpScout's sources). I fixed it in your pull request and it's working now 👌

**Comment by ukd1** [comment]
@tonyjiangh @arikfr found this googling how to use it; is there any chance of better documentation than a static image? Explaining what columns / example queries, etc would be amazing.

**Comment by susodapop** [comment]
> 
> 
> @tonyjiangh @arikfr found this googling how to use it; is there any chance of better documentation than a static image? Explaining what columns / example queries, etc would be amazing.

I'll put something together and ping you when it's done 👍

**Comment by susodapop** [comment]
@ukd1 I added a basic [example](https://redash.io/help/user-guide/visualizations/funnel-howto) to our documentation. The funnel chart is one of the easiest types to make but also the **least obvious**. I've got a blog post in the works as well with an example of some queries. Feel free to DM me or post on the Redash [user forum](discuss.redash.io) if you'd like help with a specific viz.

**Pull request merged**
