### PR TITLE
Document use of email alert template (#5996)

### PR DESCRIPTION
**Pull request by eradman**
The alert template variable `QUERY_RESULT_TABLE` was introduced to make it possible to write a generic template which includes query results.

### CODE REVIEW

**Comment by eradman** [comment]
Should apply changes suggested by restyled in the same commit?

**Comment by guidopetri** [comment]
Maybe as a separate commit, to maintain atomicity? I'll defer to Justin's opinion though

**Review by guidopetri — APPROVED** [review]

**Comment by eradman** [comment]
Very good; I pushed the restyled change as a separate commit

**Comment by justinclift** [comment]
We tend to aim for a single commit per PR (at merge time), so if a PR has multiple commits they'll get merged anyway. :smile:

**Review by justinclift — APPROVED** [review]
Eyeballing this, the description wording seems fine and there's nothing obviously wrong (to me) with the PR.

So, LGTM. :smile:

**Comment by justinclift** [comment]
Note that we shouldn't merge this until the [corresponding PR in the main redash repo](https://github.com/getredash/redash/pull/5996) is merged too.

**Comment by eradman** [comment]
Adjusted documentation to match https://github.com/getredash/redash/pull/5996

**Comment by justinclift** [comment]
Hmmm, this *was* ok to merge now yeah?  I just realised I should have asked first, just in case. :grimacing:

**Comment by eradman** [comment]
Yes, this this was ready to merge

**Comment by justinclift** [comment]
Whew!

Thanks for getting this part done too @eradman. :smile:

**Pull request merged**
